-- 053: Seed 2026 Seoul Citizen League futsal tournament.
--
-- Source:
--   https://www.sleague.or.kr/2026/futsal/
-- Public page confirms:
--   - title: 2026 생활체육 서울시민리그 풋살리그
--   - registration: 2차 2026.05.01 ~ 2026.06.07
--   - league period: 2026.06.20 ~ 2026.10.11
--   - organizer/contact footer: 서울특별시풋살연맹, 02-415-8711

INSERT INTO public.tournaments (
  sport,
  title,
  organizer,
  description,
  start_date,
  end_date,
  application_deadline,
  region,
  location,
  region_code,
  host_associations,
  host_orgs,
  host_futsal_orgs,
  division_label_local,
  division_kta_standard,
  entry_fee_unit,
  is_joint_event,
  eligible_grades,
  entry_fee,
  prize,
  format,
  player_count,
  division_gender,
  division_age_group,
  team_count_max,
  team_count_current,
  roster_min,
  roster_max,
  venue_type,
  surface_type,
  match_format,
  source_url,
  source,
  status
)
VALUES (
  'futsal',
  '2026 생활체육 서울시민리그 풋살리그',
  '서울특별시풋살연맹',
  '서울특별시와 함께하는 2026 생활체육 서울시민리그 풋살리그입니다. 공식 페이지 기준 2차 접수는 2026년 5월 1일부터 2026년 6월 7일까지이며, 리그는 2026년 6월 20일부터 2026년 10월 11일까지 진행됩니다. A조, B조, C조, D조 경기일정 및 결과와 지역·권역·결선 경기장소는 서울시민리그 공식 페이지에서 확인할 수 있습니다. 대표 연락처: 02-415-8711.',
  DATE '2026-06-20',
  DATE '2026-10-11',
  DATE '2026-06-07',
  '서울',
  '서울시민리그 풋살 공식 경기장소',
  'seoul_metro',
  ARRAY['서울특별시풋살연맹', '서울시민리그'],
  ARRAY['local']::public.tennis_org[],
  ARRAY['sleague']::public.futsal_org[],
  '서울시민리그 풋살리그',
  NULL,
  'per_team',
  FALSE,
  ARRAY['beginner', 'intermediate', 'advanced'],
  NULL,
  NULL,
  '서울시민리그 풋살 리그전',
  5,
  NULL,
  'open',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'league',
  'https://www.sleague.or.kr/2026/futsal/',
  'manual-sleague',
  'published'
)
ON CONFLICT (source, source_url) WHERE source_url IS NOT NULL
DO UPDATE SET
  title = EXCLUDED.title,
  organizer = EXCLUDED.organizer,
  description = EXCLUDED.description,
  start_date = EXCLUDED.start_date,
  end_date = EXCLUDED.end_date,
  application_deadline = EXCLUDED.application_deadline,
  region = EXCLUDED.region,
  location = EXCLUDED.location,
  region_code = EXCLUDED.region_code,
  host_associations = EXCLUDED.host_associations,
  host_orgs = EXCLUDED.host_orgs,
  host_futsal_orgs = EXCLUDED.host_futsal_orgs,
  division_label_local = EXCLUDED.division_label_local,
  division_kta_standard = EXCLUDED.division_kta_standard,
  entry_fee_unit = EXCLUDED.entry_fee_unit,
  is_joint_event = EXCLUDED.is_joint_event,
  eligible_grades = EXCLUDED.eligible_grades,
  entry_fee = EXCLUDED.entry_fee,
  prize = EXCLUDED.prize,
  format = EXCLUDED.format,
  player_count = EXCLUDED.player_count,
  division_gender = EXCLUDED.division_gender,
  division_age_group = EXCLUDED.division_age_group,
  team_count_max = EXCLUDED.team_count_max,
  team_count_current = EXCLUDED.team_count_current,
  roster_min = EXCLUDED.roster_min,
  roster_max = EXCLUDED.roster_max,
  venue_type = EXCLUDED.venue_type,
  surface_type = EXCLUDED.surface_type,
  match_format = EXCLUDED.match_format,
  status = EXCLUDED.status,
  embedding = NULL,
  embedding_updated_at = NULL,
  updated_at = now();
